# Generated by Django 4.2.4 on 2023-08-08 00:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chatter', '0003_chat_in_group_chat_received_by_chat_sent_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='received_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_by_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='chat',
            name='sent_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_by_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
